struct task_struct {
	...
	unsigned int			__state;
	...
	unsigned int			flags;
	...
	int				prio;
	int				static_prio;
	...
	struct list_head		tasks;
	...
	struct mm_struct		*mm;
	struct mm_struct		*active_mm;
	...
	int				exit_code;
	...
	pid_t				pid;
	pid_t				tgid;
	...
	char				comm[TASK_COMM_LEN];
	...
	struct fs_struct		*fs;
	struct files_struct		*files;
	...
};
